"use server";

import { z } from "zod";
import { prisma } from "~/utils/context";

const characterSheetSchema = z.object({
  characterId: z.string(),
  userId: z.string(),
  charactername: z.string().optional().or(z.null()),
  classname: z.string().optional().or(z.null()),
  background: z.string().optional().or(z.null()),
  playername: z.string().optional().or(z.null()),
  race: z.string().optional().or(z.null()),
  alignment: z.string().optional().or(z.null()),
  level: z.number().optional().or(z.null()),
  strengthscore: z.number().optional().or(z.null()),
  dexterityscore: z.number().optional().or(z.null()),
  constitutionscore: z.number().optional().or(z.null()),
  wisdomscore: z.number().optional().or(z.null()),
  intelligencescore: z.number().optional().or(z.null()),
  charismascore: z.number().optional().or(z.null()),
  inspiration: z.boolean().optional().or(z.null()),
  proficiencybonus: z.number().optional().or(z.null()),
  strengthsave: z.number().optional().or(z.null()),
  strengthsaveprof: z.boolean().optional().or(z.null()),
  dexteritysave: z.number().optional().or(z.null()),
  dexteritysaveprof: z.boolean().optional().or(z.null()),
  constitutionsave: z.number().optional().or(z.null()),
  constitutionsaveprof: z.boolean().optional().or(z.null()),
  wisdomsave: z.number().optional().or(z.null()),
  wisdomsaveprof: z.boolean().optional().or(z.null()),
  intelligencesave: z.number().optional().or(z.null()),
  intelligencesaveprof: z.boolean().optional().or(z.null()),
  charismasave: z.number().optional().or(z.null()),
  charismasaveprof: z.boolean().optional().or(z.null()),
  acrobatics: z.number().optional().or(z.null()),
  acrobaticsexpertise: z.boolean().optional().or(z.null()),
  acrobaticsprof: z.boolean().optional().or(z.null()),
  animalhandling: z.number().optional().or(z.null()),
  animalhandlingexpertise: z.boolean().optional().or(z.null()),
  animalhandlingprof: z.boolean().optional().or(z.null()),
  arcana: z.number().optional().or(z.null()),
  arcanaexpertise: z.boolean().optional().or(z.null()),
  arcanaprof: z.boolean().optional().or(z.null()),
  athletics: z.number().optional().or(z.null()),
  athleticsexpertise: z.boolean().optional().or(z.null()),
  athleticsprof: z.boolean().optional().or(z.null()),
  deception: z.number().optional().or(z.null()),
  deceptionexpertise: z.boolean().optional().or(z.null()),
  deceptionprof: z.boolean().optional().or(z.null()),
  history: z.number().optional().or(z.null()),
  historyexpertise: z.boolean().optional().or(z.null()),
  historyprof: z.boolean().optional().or(z.null()),
  insight: z.number().optional().or(z.null()),
  insightexpertise: z.boolean().optional().or(z.null()),
  insightprof: z.boolean().optional().or(z.null()),
  intimidation: z.number().optional().or(z.null()),
  intimidationexpertise: z.boolean().optional().or(z.null()),
  intimidationprof: z.boolean().optional().or(z.null()),
  investigation: z.number().optional().or(z.null()),
  investigationexpertise: z.boolean().optional().or(z.null()),
  investigationprof: z.boolean().optional().or(z.null()),
  medicine: z.number().optional().or(z.null()),
  medicineexpertise: z.boolean().optional().or(z.null()),
  medicineprof: z.boolean().optional().or(z.null()),
  nature: z.number().optional().or(z.null()),
  natureexpertise: z.boolean().optional().or(z.null()),
  natureprof: z.boolean().optional().or(z.null()),
  perception: z.number().optional().or(z.null()),
  perceptionexpertise: z.boolean().optional().or(z.null()),
  perceptionprof: z.boolean().optional().or(z.null()),
  performance: z.number().optional().or(z.null()),
  performanceexpertise: z.boolean().optional().or(z.null()),
  performanceprof: z.boolean().optional().or(z.null()),
  persuasion: z.number().optional().or(z.null()),
  persuasionexpertise: z.boolean().optional().or(z.null()),
  persuasionprof: z.boolean().optional().or(z.null()),
  religion: z.number().optional().or(z.null()),
  religionexpertise: z.boolean().optional().or(z.null()),
  religionprof: z.boolean().optional().or(z.null()),
  sleightofhand: z.number().optional().or(z.null()),
  sleightofhandexpertise: z.boolean().optional().or(z.null()),
  sleightofhandprof: z.boolean().optional().or(z.null()),
  stealth: z.number().optional().or(z.null()),
  stealthexpertise: z.boolean().optional().or(z.null()),
  stealthprof: z.boolean().optional().or(z.null()),
  survival: z.number().optional().or(z.null()),
  survivalexpertise: z.boolean().optional().or(z.null()),
  survivalprof: z.boolean().optional().or(z.null()),
  passiveperception: z.number().optional().or(z.null()),
  otherprofs: z.string().optional().or(z.null()),
  ac: z.number().optional().or(z.null()),
  initiative: z.number().optional().or(z.null()),
  speed: z.number().optional().or(z.null()),
  maxhp: z.number().optional().or(z.null()),
  currenthp: z.number().optional().or(z.null()),
  temphp: z.number().optional().or(z.null()),
  totalhd: z.string().optional().or(z.null()),
  remaininghd: z.number().optional().or(z.null()),
  deathsuccess1: z.boolean().optional().or(z.null()),
  deathsuccess2: z.boolean().optional().or(z.null()),
  deathsuccess3: z.boolean().optional().or(z.null()),
  deathfail1: z.boolean().optional().or(z.null()),
  deathfail2: z.boolean().optional().or(z.null()),
  deathfail3: z.boolean().optional().or(z.null()),
  atkname1: z.string().optional().or(z.null()),
  atkbonus1: z.number().optional().or(z.null()),
  atkdamage1: z.string().optional().or(z.null()),
  atkname2: z.string().optional().or(z.null()),
  atkbonus2: z.number().optional().or(z.null()),
  atkdamage2: z.string().optional().or(z.null()),
  atkname3: z.string().optional().or(z.null()),
  atkbonus3: z.number().optional().or(z.null()),
  atkdamage3: z.string().optional().or(z.null()),
  cp: z.number().optional().or(z.null()),
  sp: z.number().optional().or(z.null()),
  ep: z.number().optional().or(z.null()),
  gp: z.number().optional().or(z.null()),
  pp: z.number().optional().or(z.null()),
  equipmentlist: z.string().optional().or(z.null()),
  personality: z.string().optional().or(z.null()),
  ideals: z.string().optional().or(z.null()),
  bonds: z.string().optional().or(z.null()),
  flaws: z.string().optional().or(z.null()),
  features: z.string().optional().or(z.null()),
});

type CharacterSheetData = z.infer<typeof characterSheetSchema>;

export const updateCharacterSheet = async ({
  characterId,
  userId,
  charactername,
  classname,
  background,
  playername,
  race,
  alignment,
  level,
  strengthscore,
  dexterityscore,
  constitutionscore,
  wisdomscore,
  intelligencescore,
  charismascore,
  inspiration,
  proficiencybonus,
  strengthsave,
  strengthsaveprof,
  dexteritysave,
  dexteritysaveprof,
  constitutionsave,
  constitutionsaveprof,
  wisdomsave,
  wisdomsaveprof,
  intelligencesave,
  intelligencesaveprof,
  charismasave,
  charismasaveprof,
  acrobatics,
  acrobaticsexpertise,
  acrobaticsprof,
  animalhandling,
  animalhandlingexpertise,
  animalhandlingprof,
  arcana,
  arcanaexpertise,
  arcanaprof,
  athletics,
  athleticsexpertise,
  athleticsprof,
  deception,
  deceptionexpertise,
  deceptionprof,
  history,
  historyexpertise,
  historyprof,
  insight,
  insightexpertise,
  insightprof,
  intimidation,
  intimidationexpertise,
  intimidationprof,
  investigation,
  investigationexpertise,
  investigationprof,
  medicine,
  medicineexpertise,
  medicineprof,
  nature,
  natureexpertise,
  natureprof,
  perception,
  perceptionexpertise,
  perceptionprof,
  performance,
  performanceexpertise,
  performanceprof,
  persuasion,
  persuasionexpertise,
  persuasionprof,
  religion,
  religionexpertise,
  religionprof,
  sleightofhand,
  sleightofhandexpertise,
  sleightofhandprof,
  stealth,
  stealthexpertise,
  stealthprof,
  survival,
  survivalexpertise,
  survivalprof,
  passiveperception,
  otherprofs,
  ac,
  initiative,
  speed,
  maxhp,
  currenthp,
  temphp,
  totalhd,
  remaininghd,
  deathsuccess1,
  deathsuccess2,
  deathsuccess3,
  deathfail1,
  deathfail2,
  deathfail3,
  atkname1,
  atkbonus1,
  atkdamage1,
  atkname2,
  atkbonus2,
  atkdamage2,
  atkname3,
  atkbonus3,
  atkdamage3,
  cp,
  sp,
  ep,
  gp,
  pp,
  equipmentlist,
  personality,
  ideals,
  bonds,
  flaws,
  features,
}: CharacterSheetData) => {
  const character = await prisma.character.update({
    where: {
      id: characterId,
    },
    data: {
      userId: userId,
      charname: charactername,
      classname: classname,
      background: background,
      playername: playername,
      race: race,
      alignment: alignment,
      level: level,
      strengthscore: strengthscore,
      dexterityscore: dexterityscore,
      constitutionscore: constitutionscore,
      wisdomscore: wisdomscore,
      intelligencescore: intelligencescore,
      charismascore: charismascore,
      inspiration: inspiration,
      proficiencybonus: proficiencybonus,
      strengthsave: strengthsave,
      strengthsaveprof: strengthsaveprof,
      dexteritysave: dexteritysave,
      dexteritysaveprof: dexteritysaveprof,
      constitutionsave: constitutionsave,
      constitutionsaveprof: constitutionsaveprof,
      wisdomsave: wisdomsave,
      wisdomsaveprof: wisdomsaveprof,
      intelligencesave: intelligencesave,
      intelligencesaveprof: intelligencesaveprof,
      charismasave: charismasave,
      charismasaveprof: charismasaveprof,
      acrobatics: acrobatics,
      acrobaticsexpertise: acrobaticsexpertise,
      acrobaticsprof: acrobaticsprof,
      animalhandling: animalhandling,
      animalhandlingexpertise: animalhandlingexpertise,
      animalhandlingprof: animalhandlingprof,
      arcana: arcana,
      arcanaexpertise: arcanaexpertise,
      arcanaprof: arcanaprof,
      athletics: athletics,
      athleticsexpertise: athleticsexpertise,
      athleticsprof: athleticsprof,
      deception: deception,
      deceptionexpertise: deceptionexpertise,
      deceptionprof: deceptionprof,
      history: history,
      historyexpertise: historyexpertise,
      historyprof: historyprof,
      insight: insight,
      insightexpertise: insightexpertise,
      insightprof: insightprof,
      intimidation: intimidation,
      intimidationexpertise: intimidationexpertise,
      intimidationprof: intimidationprof,
      investigation: investigation,
      investigationexpertise: investigationexpertise,
      investigationprof: investigationprof,
      medicine: medicine,
      medicineexpertise: medicineexpertise,
      medicineprof: medicineprof,
      nature: nature,
      natureexpertise: natureexpertise,
      natureprof: natureprof,
      perception: perception,
      perceptionexpertise: perceptionexpertise,
      perceptionprof: perceptionprof,
      performance: performance,
      performanceexpertise: performanceexpertise,
      performanceprof: performanceprof,
      persuasion: persuasion,
      persuasionexpertise: persuasionexpertise,
      persuasionprof: persuasionprof,
      religion: religion,
      religionexpertise: religionexpertise,
      religionprof: religionprof,
      sleightofhand: sleightofhand,
      sleightofhandexpertise: sleightofhandexpertise,
      sleightofhandprof: sleightofhandprof,
      stealth: stealth,
      stealthexpertise: stealthexpertise,
      stealthprof: stealthprof,
      survival: survival,
      survivalexpertise: survivalexpertise,
      survivalprof: survivalprof,
      passiveperception: passiveperception,
      otherprofs: otherprofs,
      ac: ac,
      initiative: initiative,
      speed: speed,
      maxhp: maxhp,
      currenthp: currenthp,
      temphp: temphp,
      totalhd: totalhd,
      remaininghd: remaininghd,
      deathsuccess1: deathsuccess1,
      deathsuccess2: deathsuccess2,
      deathsuccess3: deathsuccess3,
      deathfail1: deathfail1,
      deathfail2: deathfail2,
      deathfail3: deathfail3,
      atkname1: atkname1,
      atkbonus1: atkbonus1,
      atkdamage1: atkdamage1,
      atkname2: atkname2,
      atkbonus2: atkbonus2,
      atkdamage2: atkdamage2,
      atkname3: atkname3,
      atkbonus3: atkbonus3,
      atkdamage3: atkdamage3,
      cp: cp,
      sp: sp,
      ep: ep,
      gp: gp,
      pp: pp,
      equipmentlist: equipmentlist,
      personality: personality,
      ideals: ideals,
      bonds: bonds,
      flaws: flaws,
      features: features,
    },
  });
};
