"use server";

import { revalidatePath } from "next/cache";
import { z } from "zod";
import { prisma } from "~/utils/context";
import { characterSheetSchema } from "~/lib/validations/characterSheet";

type CharacterSheetData = z.infer<typeof characterSheetSchema>;

interface Response {
  status: "SUCCESS" | "ERROR" | "FAILED";
  message: string;
}

export const updateCharacterSheet = async ({
  characterId,
  userId,
  charactername,
  classname,
  background,
  playername,
  race,
  alignment,
  level,
  strengthscore,
  dexterityscore,
  constitutionscore,
  wisdomscore,
  intelligencescore,
  charismascore,
  inspiration,
  proficiencybonus,
  strengthsave,
  strengthsaveprof,
  dexteritysave,
  dexteritysaveprof,
  constitutionsave,
  constitutionsaveprof,
  wisdomsave,
  wisdomsaveprof,
  intelligencesave,
  intelligencesaveprof,
  charismasave,
  charismasaveprof,
  acrobatics,
  acrobaticsexpertise,
  acrobaticsprof,
  animalhandling,
  animalhandlingexpertise,
  animalhandlingprof,
  arcana,
  arcanaexpertise,
  arcanaprof,
  athletics,
  athleticsexpertise,
  athleticsprof,
  deception,
  deceptionexpertise,
  deceptionprof,
  history,
  historyexpertise,
  historyprof,
  insight,
  insightexpertise,
  insightprof,
  intimidation,
  intimidationexpertise,
  intimidationprof,
  investigation,
  investigationexpertise,
  investigationprof,
  medicine,
  medicineexpertise,
  medicineprof,
  nature,
  natureexpertise,
  natureprof,
  perception,
  perceptionexpertise,
  perceptionprof,
  performance,
  performanceexpertise,
  performanceprof,
  persuasion,
  persuasionexpertise,
  persuasionprof,
  religion,
  religionexpertise,
  religionprof,
  sleightofhand,
  sleightofhandexpertise,
  sleightofhandprof,
  stealth,
  stealthexpertise,
  stealthprof,
  survival,
  survivalexpertise,
  survivalprof,
  passiveperception,
  otherprofs,
  ac,
  initiative,
  speed,
  maxhp,
  currenthp,
  temphp,
  totalhd,
  remaininghd,
  deathsuccess1,
  deathsuccess2,
  deathsuccess3,
  deathfail1,
  deathfail2,
  deathfail3,
  atkname1,
  atkbonus1,
  atkdamage1,
  atkname2,
  atkbonus2,
  atkdamage2,
  atkname3,
  atkbonus3,
  atkdamage3,
  cp,
  sp,
  ep,
  gp,
  pp,
  equipmentlist,
  personality,
  ideals,
  bonds,
  flaws,
  features,
}: CharacterSheetData): Promise<Response | undefined> => {
  await prisma.character.update({
    where: {
      id: characterId,
    },
    data: {
      userId: userId,
      charname: charactername,
      classname: classname,
      background: background,
      playername: playername,
      race: race,
      alignment: alignment,
      level: level,
      strengthscore: strengthscore,
      dexterityscore: dexterityscore,
      constitutionscore: constitutionscore,
      wisdomscore: wisdomscore,
      intelligencescore: intelligencescore,
      charismascore: charismascore,
      inspiration: inspiration,
      proficiencybonus: proficiencybonus,
      strengthsave: strengthsave,
      strengthsaveprof: strengthsaveprof,
      dexteritysave: dexteritysave,
      dexteritysaveprof: dexteritysaveprof,
      constitutionsave: constitutionsave,
      constitutionsaveprof: constitutionsaveprof,
      wisdomsave: wisdomsave,
      wisdomsaveprof: wisdomsaveprof,
      intelligencesave: intelligencesave,
      intelligencesaveprof: intelligencesaveprof,
      charismasave: charismasave,
      charismasaveprof: charismasaveprof,
      acrobatics: acrobatics,
      acrobaticsexpertise: acrobaticsexpertise,
      acrobaticsprof: acrobaticsprof,
      animalhandling: animalhandling,
      animalhandlingexpertise: animalhandlingexpertise,
      animalhandlingprof: animalhandlingprof,
      arcana: arcana,
      arcanaexpertise: arcanaexpertise,
      arcanaprof: arcanaprof,
      athletics: athletics,
      athleticsexpertise: athleticsexpertise,
      athleticsprof: athleticsprof,
      deception: deception,
      deceptionexpertise: deceptionexpertise,
      deceptionprof: deceptionprof,
      history: history,
      historyexpertise: historyexpertise,
      historyprof: historyprof,
      insight: insight,
      insightexpertise: insightexpertise,
      insightprof: insightprof,
      intimidation: intimidation,
      intimidationexpertise: intimidationexpertise,
      intimidationprof: intimidationprof,
      investigation: investigation,
      investigationexpertise: investigationexpertise,
      investigationprof: investigationprof,
      medicine: medicine,
      medicineexpertise: medicineexpertise,
      medicineprof: medicineprof,
      nature: nature,
      natureexpertise: natureexpertise,
      natureprof: natureprof,
      perception: perception,
      perceptionexpertise: perceptionexpertise,
      perceptionprof: perceptionprof,
      performance: performance,
      performanceexpertise: performanceexpertise,
      performanceprof: performanceprof,
      persuasion: persuasion,
      persuasionexpertise: persuasionexpertise,
      persuasionprof: persuasionprof,
      religion: religion,
      religionexpertise: religionexpertise,
      religionprof: religionprof,
      sleightofhand: sleightofhand,
      sleightofhandexpertise: sleightofhandexpertise,
      sleightofhandprof: sleightofhandprof,
      stealth: stealth,
      stealthexpertise: stealthexpertise,
      stealthprof: stealthprof,
      survival: survival,
      survivalexpertise: survivalexpertise,
      survivalprof: survivalprof,
      passiveperception: passiveperception,
      otherprofs: otherprofs,
      ac: ac,
      initiative: initiative,
      speed: speed,
      maxhp: maxhp,
      currenthp: currenthp,
      temphp: temphp,
      totalhd: totalhd,
      remaininghd: remaininghd,
      deathsuccess1: deathsuccess1,
      deathsuccess2: deathsuccess2,
      deathsuccess3: deathsuccess3,
      deathfail1: deathfail1,
      deathfail2: deathfail2,
      deathfail3: deathfail3,
      atkname1: atkname1,
      atkbonus1: atkbonus1,
      atkdamage1: atkdamage1,
      atkname2: atkname2,
      atkbonus2: atkbonus2,
      atkdamage2: atkdamage2,
      atkname3: atkname3,
      atkbonus3: atkbonus3,
      atkdamage3: atkdamage3,
      cp: cp,
      sp: sp,
      ep: ep,
      gp: gp,
      pp: pp,
      equipmentlist: equipmentlist,
      personality: personality,
      ideals: ideals,
      bonds: bonds,
      flaws: flaws,
      features: features,
    },
  });
  revalidatePath(`character/${characterId}`)
  return {status: "SUCCESS", message: "Updated character sheet."}
};
