import Head from "next/head";
import { api } from "~/utils/api";
import { UserButton } from "@clerk/nextjs";
import CharacterCreation from "~/components/characterCreation";

export default function Home() {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center space-y-3 justify-center ">
        <CharacterCreation />
        {/* <UserButton /> */}
      </main>
    </>
  );
}
