import Head from "next/head";


export default function Home() {
  

  return (
    <>
      <Head>
        <title>Quest Bazaar</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center space-y-3 justify-center ">
        
        {/* <CharacterCreation /> */}
      </main>
    </>
  );
}
